### PR TITLE
Another QOL Update

### PR DESCRIPTION
**Pull request by danmarzola**
I made a few modification to show more information on screen, as i added a new option to use return and mender at Eulmore

image

Also include a json file with all Unspoiled Nodes from ARR to ShadowBringers, allowing check if a crafting tree need a unspoiled item in new row

image

And just for information add a few information to scenario form like:

Gathering Unspoiled Node: Gold Ore
Expansion: ARR
Time(ET): 09:00
Location: Eastern Thanalan
Coordinate: (x28,y22)

### CODE REVIEW

**Comment by ShishioValentine** [comment]
Looks good !
I will check why the test units are KO. Probably because of the added information in the script and/or the eulmore custom teleport.

**Comment by danmarzola** [comment]
Yeah, also i think you just need to modify a few thing, i use return() to go back to eulmore, but need to be teleporth(Eulmore) as not everyone save return on eulmore.

Also i replace teleportifnotthere for teleport, because many times i found that script dont teleport and get stucked in a wall

**Comment by ShishioValentine** [comment]
Yeah, I also saw that the test units were KO because the file UnspoiledNodes.json is not found when it runs them.
I have added the file to visual studio, so it copies it each time to the output directory automatically, as well as a try catch in the GetAllUnspoiledNodes method.

**Comment by danmarzola** [comment]
> I have added the file to visual studio, so it copies it each time to the output directory automatically, as well as a try catch in the GetAllUnspoiledNodes method.
Yeah i need be more careful about it, i not high skilled in code, but i will try improve and rework test units if i make another feature/customization.

**Comment by ShishioValentine** [comment]
No worries !
If you have any question, just send me a mail :)

**Comment by ShishioValentine** [comment]
I do not see the custom teleport/scenario for eulmore in the CustomTeleport directory.
Could you add the file ?

You have to copy them in the CustomTeleport directory at the root of the code directory. They will be automatically copied during the build into the debug/release directory.

**Comment by danmarzola** [comment]
[Eulmore Grid.txt](https://github.com/ShishioValentine/MiqoCrafter/files/4726381/Eulmore.Grid.txt)
[Eulmore Scenario.txt](https://github.com/ShishioValentine/MiqoCrafter/files/4726383/Eulmore.Scenario.txt)

Sure

**Comment by ShishioValentine** [comment]
Thanks ! I will push them

**Pull request merged**
